### ISSUE TITLE
网页版的有吗

### ISSUE THREAD

**Issue by xiaowenlv** [gfw-breaker/bn-android#1]
这个能不能和heroku的那个结合，我搭建了那个，但是不能看youtube，我就想把一些好的频道推荐给朋友。

**Comment by gfw-breaker** [comment]
@xiaowenlv 我是非专业人士，这个做的很简陋。推荐你使用 [网门](https://github.com/oGate2/oGate)，内容丰富，抗封锁能力强力。

**Comment by gfw-breaker** [comment]
@xiaowenlv 里面基本上覆盖了YouTube上所有优秀中文频道。

**Comment by xiaowenlv** [comment]
我就是想让heroku的站点可以听音频的节目，不需要那么强的抗封锁能力

2019-05-22 11:27 GMT+08:00, HelloWorld <notifications@github.com>:

**Comment by gfw-breaker** [comment]
@xiaowenlv 你在heroku那个项目里的 public/index.html 中添加音频节目的链接即可。

**Comment by xiaowenlv** [comment]
我就是没有音频的链接啊，如果要自己一个个的上传也太麻烦了

2019-05-25 8:19 GMT+08:00, 翻墙教练 <notifications@github.com>:
